name = "Lithium"
uuid = "11699399-1d6a-4a57-a226-06bcd1f14848"
authors = ["Abraham Nunes"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJScikitLearnInterface = "5ae90465-5518-4432-b9d2-8a1def2f0cab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.6.0, 1.6.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]